### PR TITLE
fix: components and explorer tree issues

### LINKED ISSUE #2972: Child mapper component names are not unique
## Description of Bug
The components created by the child mapper do not have unique names. 
The child mapper e2e should have caught this bug but seems that due to recent merges (ignoring ci) something has broken it.

## How to Reproduce

1.
2.

## Video/Screenshot Showing Bug

https://github.com/codelab-app/platform/assets/48331678/be342122-d513-41ae-a185-83dc647e1fc0

### LINKED ISSUE #3308: Can't open component props settings once an element is selected
## How to Reproduce

1. Go to components builder and open a custom component
2. The initial rendered form in the right panel for the `props` tab is for the component props
3. Click any elements of the props
4. There is no way to go back to the component props settings again (unless go back to /apps and navigate back or reload the page)

### PR DESCRIPTION
**Pull request by vladyslav-polishchuk**
## Description

A couple of problem is fixed in this PR:
1. #3308 issue is that in component builder it was impossible to open components props form after any elmenet in builder tree was selected. The issue is resolved by adding new `Components` tabs (similar to `Page` tab for page builder).

https://github.com/codelab-app/platform/assets/74900868/79972a21-f7d5-4a56-b05a-b7a9c9dc36a0

2. Builder tree issues. The child mapper components, regular components was displaying incorrectly.

https://github.com/codelab-app/platform/assets/74900868/c806e94f-673a-4521-b271-2596f7271c99

## Related Issue(s)

Fixes #3308
Fixes #2972

### CODE REVIEW

File: apps/platform/pages/apps/[userSlug]/[appSlug]/pages/[pageSlug]/builder.tsx [hunk 1]
```diff
@@ -67,7 +67,6 @@ const PageBuilderView: CodelabPage = observer(() => {
         ],
       }}
       contentStyles={contentStyles}
-      headerHeight={48}
```
Comment (vladyslav-polishchuk) [inline apps/platform/pages/apps/[userSlug]/[appSlug]/pages/[pageSlug]/builder.tsx:70]: No need to pass the header height, it is not used anyhow

File: libs/frontend/application/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPaneInspectorTabContainer.tsx [hunk 2]
```diff
@@ -83,8 +86,10 @@ export const ConfigPaneInspectorTabContainer = observer(() => {
             runtimeElement={selectedNode}
           />
         </>
-      ) : (
+      ) : isNil(selectedNode.childMapperIndex) ? (
         <UpdateComponentForm runtimeComponent={selectedNode} />
+      ) : (
+        'Child Mapper Component Props cannot be edited'
```
Comment (vladyslav-polishchuk) [inline libs/frontend/application/builder/src/sections/config-pane/ConfigPane-InspectorTabContainer/ConfigPaneInspectorTabContainer.tsx:92]: When the child mapper component is selected in builder - we should not allow update component props

File: libs/frontend/application/element/src/use-cases/element/update-element/UpdateElementForm.tsx [hunk 3]
```diff
@@ -90,29 +128,7 @@ export const UpdateElementForm = observer<UpdateElementFormProps>(
               'name',
             ]}
           />
-          <Collapse defaultActiveKey={expandedFields}>
```
Comment (vladyslav-polishchuk) [inline libs/frontend/application/element/src/use-cases/element/update-element/UpdateElementForm.tsx:93]: Antd throws error in the console saying that this is an obsolete way to use the component and it will be removed in the next major release

File: libs/frontend/application/renderer/src/model/runtime-element.model.ts [hunk 4]
```diff
@@ -236,7 +237,7 @@ export class RuntimeElementModel
           this.element.current.setRenderingError(null)
         },
       },
-      key: this.element.id,
```
Comment (vladyslav-polishchuk) [inline libs/frontend/application/renderer/src/model/runtime-element.model.ts:239]: A fix for duplicated keys when child mapper components are rendered

File: libs/frontend/application/renderer/src/model/runtime-element.model.ts [hunk 5]
```diff
@@ -382,10 +383,12 @@ export class RuntimeElementModel
       }
     })
 
-    const children = [
-      ...this.children.map((child) => child.treeViewNode),
-      ...reactNodesChildren,
-    ]
+    const children = isComponentRef(this.element.current.renderType)
```
Comment (vladyslav-polishchuk) [inline libs/frontend/application/renderer/src/model/runtime-element.model.ts:386]: A fix to not render component children in builder. Just the root component node should appear in builder
