### PR TITLE
fix: not authenticated error on page regeneration

### LINKED ISSUE #2232: Extract functionality of _sites to separate project
## Description
Currently, builder and production user pages share the same project and this causes a couple of problems:
1. middleware.ts is always executed for requests to the builder and to _sites, but if split into two separate projects - this middleware is not needed at all.
2. _app.tsx file adds a lot of code that is used mostly for builder functionality and is not needed for user pages. So splitting may reduce bundle size for user apps

### PR DESCRIPTION
**Pull request by vladyslav-polishchuk**
## Description
- fixed auth0 403 error when requested to regenerate app pages.
Now the flow is the following:
user clicks the "rebuild" button on UI -> request to the builder backend is sent (admin.codelab.app) -> builder backend redirects the request to the appropriate domain of the websites project (for example to codelab-demo.online/api/regenerate). Each backend endpoint is protected by auth0 so an unauthenticated user will not be able to trigger the regeneration of any page.

- fixed website page routing after automatic slugs were implemented
after automatic slugs were implemented it became hard to navigate to user pages since they started to look like this: `https://codelab-demo.online/3-fe-3-e-3-b-3-0852-4056-9625-d-7-ba-490-a-125-a-home`. Used slugified page name to navigate to pages instead

## Related Issue(s)

Fixes #2232

### CODE REVIEW

File: apps/websites/pages/api/regenerate.ts [hunk 1]
```diff
@@ -23,7 +24,8 @@ const regenerate: NextApiHandler = async (req, res) => {
     const revalidatedPages: Array<string> = []
     const failedPages: Array<string> = []
 
-    const revalidationPromises = pages.map(async (pageSlug) => {
+    const revalidationPromises = pages.map(async (pageName) => {
+      const pageSlug = slugify(pageName)
```
Comment (webberwang) [inline apps/websites/pages/api/regenerate.ts:28]: We actually have a computed slug from the graphql api we could use

Comment (webberwang) [reply apps/websites/pages/api/regenerate.ts:28]: Same for all other models

**Review by webberwang — CHANGES_REQUESTED** [review]
