### PR TITLE
fix: cannot use UnionType inside ArrayType

### LINKED ISSUE #2663: Cannot use UnionType
## Current Behavior
Cannot use `UnionType` inside `ArrayType`.
Here `Test Font` type is a union type of two other `InterfaceType`s.

## Video Showing Bug

https://github.com/codelab-app/platform/assets/48331678/99d35641-008e-4ca2-9e1a-88979368a823

### PR DESCRIPTION
**Pull request by melhamin**
## Related Issue(s)

Fixes #2663

### CODE REVIEW

File: libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx [hunk 1]
```diff
@@ -47,8 +47,11 @@ export const SelectUnionTypeValue = (props: SelectUnionTypeValueProps) => {
   const { name } = props
   const [fieldProps, context] = useField(name, props)
   const oneOf = fieldProps.field.oneOf
-  const typeFieldName = `${name}.type`
-  const valueFieldName = `${name}.value`
+  // For the nested fields i.e. UnionType inside ArrayType, the name seems to be empty
+  // this causes the field not be validated correctly against the schema
+  // hence `type` would is valid not "".type
+  const typeFieldName = name ? `${name}.type` : 'type'
```
Comment (webberwang) [inline libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx:53]: is there a way to add the name for nested? feels solution should be closer to where the UnionType creates the field type name

Comment (melhamin) [reply libs/frontend/domain/type/src/interface-form/fields/select-union-type-value/SelectUnionTypeValue.tsx:53]: I don't like this solution either tbh, the problem is that we don't pass the field type name manually, it's generated internally by uniforms from the JsoneSchema created for the type.

I inspected the uniform's source code but couldn't figure out what could be the reason for this behavior.

If you think it's too hacky I will keep looking more into it.
