### PR TITLE
fix: static page regeneration issue

### LINKED ISSUE #1617: Enable custom domains for apps
- [x] First need to namespace each url with username

The static props are compiled at build time, so we'll either need the server up and running during build, or have the data already as a json file.

During local push, we'll ideally use json data (since it's harder to run a server during local flow, need to use concurrently and gets messy).

But we'll need to have 2 separate methods of fetching data within getStaticProps. The code will be simpler if we defer the complexity to the dev, having him run a test server manually.

But this may interfere with the e2e server that is ran. Perhaps not since the wait-on requires a 3001 running, we would just remove the e2e server command since we already require a server.

---

Branch: `1617-custom-domains`

The dynamic route is under `_sites`, you can create 2 pages with Text atom only to see it working.

---

- [x] Enable custom domains

So we have created an application with pages `http://codelab.ai/user/app/home` & `http://codelab.ai/user/app/about`

We would want to make it such that accessing a custom domain `http://example.com` would link to `http://codelab.ai/user/app/page-1` and `http://example.com/about` would link to `http://codelab.ai/user/app/about`

Keep in mind, the browser URL bar would display our custom domain, while the content of the web page will display the pages

---

To achieve this, we will use Next.js's hostname rewrite. I've created a custom example here

https://github.com/codelab-ai/hostname-rewrite

Under https://github.com/codelab-ai/hostname-rewrite/tree/codelab-hostname-rewrite/edge-functions/hostname-rewrites

This repo is deployed here https://vercel.com/codelabai/hostname-rewrites

---

Essentially I have purchased the domain `http://codelab.llc`, this is our main site, then other custom domains can point to subdomains of this site.

Each user of codelab would be assigned a subdomain, this can be created programmatically using API

### PR DESCRIPTION
**Pull request by vladyslav-polishchuk**
## Description
Manual static page regeneration of user pages works only when executed on the user domain. So for example, if we want to regenerate some pages for `some-user-app.com` domain - we should specify the header with the domain name, even though they share the same codebase.

## Video or Image

https://user-images.githubusercontent.com/74900868/218331515-313809a0-cd03-45d8-9256-ebcfaf6b5bfa.mov

## Related Issue(s)

Fixes #1617

### CODE REVIEW

File: apps/builder/pages/api/regenerate.ts [hunk 1]
```diff
@@ -91,15 +100,22 @@ const regenerate: NextApiHandler = async (req, res) => {
     const revalidatedPages: Array<string> = []
     const failedPages: Array<string> = []
 
-    const revalidationPromises = pathsToRevalidate.map(async (path) => {
-      try {
-        await res.revalidate(path)
+    const revalidationPromises = pathsToRevalidate.map(
+      async ({ path, domain }) => {
```
Comment (webberwang) [inline apps/builder/pages/api/regenerate.ts:104]: I would pass domain/page to this function, and compute the path here. better to keep entity as a whole for as long as possible (down the function chain)

**Review by webberwang — CHANGES_REQUESTED** [review]
