### PR TITLE
fix: remove duplicate form components on export

### LINKED ISSUE #2504: Component included in app export multiple times
## Current Behavior
`yarn cli data export`

If the component is used on multiple pages - it will be included in the export file several times. This also causes a "Constraint validation" error on an attempt to import such an app

## Video Showing Bug

https://user-images.githubusercontent.com/74900868/233015769-d4b00626-4f7b-43d1-a167-bfe13b72ccba.mov

### PR DESCRIPTION
**Pull request by amrmuhamedd**
## Description
remove duplicate from components on export app

## Before

https://user-images.githubusercontent.com/47860740/235043638-e4255313-f890-4ff9-a04f-72b495e7f696.mp4

## After

https://user-images.githubusercontent.com/47860740/235319478-07656f09-bbea-4008-9d29-42f8978ac963.mp4

## after import app 

https://user-images.githubusercontent.com/47860740/235319503-0222c9ab-4264-46c7-ba79-82057d891a48.mp4

## Related Issue(s)

- #2504 

Fixes #2504

### CODE REVIEW

**Review by webberwang — CHANGES_REQUESTED** [review]
page_repo_ts_—_platform

Solution should filter at the source instead

File: libs/backend/abstract/core/src/app.interface.ts [hunk 1]
```diff
@@ -11,3 +11,7 @@ export type IAppExport = Pick<OGM_TYPES.App, 'id' | 'name' | 'slug'> & {
 export interface ExportAppData {
   app: IAppExport
 }
+
+export interface IExportComponents {
```
Comment (webberwang) [inline libs/backend/abstract/core/src/app.interface.ts:15]: should put in components file

File: libs/backend/application/user/src/use-case/export-user-data.ts [hunk 2]
```diff
@@ -9,9 +9,11 @@ export const exportUserData = async (where: OGM_TYPES.AppWhere) => {
   // TODO: Need to export only types used by app
   const typesData = await exportUserTypes()
   const resourcesData = await exportResources()
+  const components = await exportComponents(where)
 
   const exportData: IUserDataExport = {
     apps: appsData,
+    components: components,
```
Comment (webberwang) [inline libs/backend/application/user/src/use-case/export-user-data.ts:16]: unnecessary object notation

File: libs/backend/domain/app/src/repository/app.repo.ts [hunk 3]
```diff
@@ -111,54 +125,57 @@ export const createApp = async (app: IAppExport, owner: IAuth0Owner) => {
...
+  for (const component of components) {
+    await interfaceTypeRepository
+      .add([
+        { ...component.store.api, fields: [] },
+        { ...component.api, fields: [] },
+      ])
+      .catch((err) => console.log({ err }))
+    await fieldRepository.add(component.api.fields).catch((err) => null)
+    await fieldRepository.add(component.store.api.fields).catch((err) => null)
+    await storeRepository.add([component.store]).catch((err) => null)
```
Comment (webberwang) [inline libs/backend/domain/app/src/repository/app.repo.ts:169]: no need to catch here, since we're not doing anything with the catch

File: libs/backend/domain/app/src/repository/app.repo.ts [hunk 4]
```diff
@@ -209,3 +225,24 @@ export const getApp = async (app: OGM_TYPES.App): Promise<ExportAppData> => {
...
   }
 }
+
+// export component of the app
+
+export const getComponents = async (
+  app: OGM_TYPES.App,
+): Promise<IExportComponents> => {
+  const pageRepository = new PageRepository()
+  const pages = await pageRepository.find({ app: { id: app.id } })
```
Comment (webberwang) [inline libs/backend/domain/app/src/repository/app.repo.ts:235]: Try to move this to ComponentRepository.find(), and pass in component where to this function

File: libs/backend/application/user/src/use-case/import-user-data.ts [hunk 5]
```diff
@@ -8,9 +8,9 @@ export const importUserData = async (
   data: IUserDataExport,
   owner: IAuth0Owner,
 ) => {
-  const { apps, resources } = data
+  const { apps, components, resources } = data
 
   await importResources(resources, owner)
 
-  await importApps(apps, owner)
+  await importApps(apps, components, owner)
```
Comment (webberwang) [inline libs/backend/application/user/src/use-case/import-user-data.ts:15]: components belong to a user, so importing components should go under `importUserData`

File: libs/backend/application/app/src/use-case/import-apps.ts [hunk 6]
```diff
@@ -1,17 +1,21 @@
...
 export const importApps = async (
   apps: Array<IAppExport> = [],
+  components: Array<IComponentExport>,
   owner: IAuth0Owner,
 ) => {
   logSection('Importing App')
 
   for (const app of apps) {
-    const importedApp = await createApp(app, owner)
+    const importedApp = await createApp(app, components, owner)
```
Comment (webberwang) [inline libs/backend/application/app/src/use-case/import-apps.ts:18]: component is scoped under user

File: libs/backend/application/app/src/use-case/export-components.ts [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+import flatMap from 'lodash/flatMap'
+import uniqBy from 'lodash/uniqBy'
+
+export const exportComponents = async (where: OGM_TYPES.AppWhere) => {
+  const appRepository = new AppRepository()
+  const apps = await appRepository.find(where)
+
+  const components = await Promise.all(
+    apps.map(async (app) => {
+      const { components: Exportedcomponent } = await getComponents(app)
```
Comment (webberwang) [inline libs/backend/application/app/src/use-case/export-components.ts:12]: this function should call componentRepository like `export-app`

**Review by webberwang — CHANGES_REQUESTED** [review]

File: libs/backend/domain/app/src/repository/app.repo.ts (hunk 3 above)
Comment (amrmuhamedd) [reply libs/backend/domain/app/src/repository/app.repo.ts:169]: if no catch and user have a app it return error validation constrain I add catch to continue and update the app if exist
