### PR TITLE
feat: production websites fixes and enhancements

### LINKED ISSUE #3287: Refactor build app
## Description

BuildAppModal_tsx_—_platform

Move shared logic under `appService.regeneratePages()` or something similar

### PR DESCRIPTION
**Pull request by vladyslav-polishchuk**
## Description

- Added Cypress test that checks if user app is available in production
- Fix script error in production websites when URLs were concatenated incorrectly
- Refactored app/pages build functionality to not duplicate code
- Fixed graphql query that used duplicated elements
- Improved error/success handling when app/pages is build for production

## Related Issue(s)

Fixes #3287 
Also part of #3063

### CODE REVIEW

File: libs/shared/config/src/env/services/endpoint.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export class EndpointEnvVars implements IEndpointEnvVars {
    * URL is protocol + origin
    */
   get canActivateUrl() {
-    return `${this.platformApiHost}/api/can-activate`
+    return new URL('api/can-activate', this.platformApiHost).toString()
```
Comment (vladyslav-polishchuk) [inline libs/shared/config/src/env/services/endpoint.ts:36]: Use `URL` constructor to create url strings. This allows to avoid invalid concatenation and as a result - invalid urls like `admin.codelab.app//api/can-activate`

File: terraform/modules/digitalocean-codelab/platform-api.tf [hunk 2]
```diff
@@ -9,6 +9,7 @@ resource "digitalocean_app" "platform-api" {
     }
 
     service {
+      instance_size_slug = "basic-xxs"
```
Comment (vladyslav-polishchuk) [inline terraform/modules/digitalocean-codelab/platform-api.tf:12]: Adding this just to avoid diff during `terraform plan/terraform apply`. This is the smallest instance and this is the same value that is used by default

Comment (webberwang) [reply terraform/modules/digitalocean-codelab/platform-api.tf:12]: I see just for testing in the meantime

File: libs/shared/config/src/env/services/endpoint.ts (hunk 1 above)
Comment (webberwang) [reply libs/shared/config/src/env/services/endpoint.ts:36]: Sure seems better
