### PR TITLE
fix: builder general fixes [Part 1]

### LINKED ISSUE #3688: Builder general fixes

### PR DESCRIPTION
**Pull request by assimhabeek**
## Description

- Fix bad call of  `setState` in builder
- Fix `PropForm` validation issue
- Fix `ElementCssEditor`
- Improved tab constant 
- Moved `expressionTransformer` to service, 
- Depending on runtimeElement changing to ref, 
- Splitting the init and computed
## Related Issue(s)

Fixes #3688

### CODE REVIEW

File: libs/frontend/application/page/src/use-cases/get-pages/PageTreeItem.tsx [hunk 1]
```diff
@@ -69,7 +71,16 @@ export const PageTreeItem = observer(
         confirmText: `Are you sure you want to delete "${page.name}"?`,
         cuiKey: UiKey.PageToolbarItemDelete,
         icon: <DeleteOutlined />,
-        onClick: () => removeMany([page]),
+        onClick: () => {
+          const activeRenderer = rendererService.activeRenderer?.current
+          const currentPage = activeRenderer?.containerNode.current
+
+          if (currentPage?.id === page.id) {
+            void removeAndNavigate(page)
```
Comment (webberwang) [inline libs/frontend/application/page/src/use-cases/get-pages/PageTreeItem.tsx:79]: can this reuse removeMany logic? and call navigate directly

**Review by webberwang — CHANGES_REQUESTED** [review]
